### ISSUE TITLE
MovingLight 崩服

### ISSUE THREAD

**Issue by MengYang8481** [Redbeanw44602/LiteLoaderMods#1]
关服时大概率崩溃
![UK ~X{$D2P9}4B)8M~2_J7W](https://user-images.githubusercontent.com/23436744/163659869-eda52ee3-cb3b-4c2e-bb43-b76144a5f3de.jpg)
![image](https://user-images.githubusercontent.com/23436744/163659903-5de65305-34d0-4325-a268-793647eefb4e.png)
BDS 1.18.12 ，LL 2.1.7 ，插件版本最新
根据群友描述疑似光源假方块没有及时得到清理（？

**Comment by Redbeanw44602** [comment]
无法复现此问题，请升级最新版后尝试，并检查与其他插件是否存在冲突。

若问题仍然存在，请提供完整复现方法并重新打开issue。
